config/routes.rb
Rails.application.routes.draw do
  constraints(AdminDomainConstraint.new) do
    scope module: 'admin' do
      devise_for :users, controllers: {
        sessions: 'admin/devise/sessions',
        confirmations: 'admin/devise/confirmations',
        mailers: 'admin/devise/mailers',
        passwords: 'admin/devise/passwords',
        registrations: 'admin/devise/registrations',
        shared: 'admin/devise/shared',
        unlocks: 'admin/devise/unlocks'
      }, as: :admin
      resources :users
      resources :home
      resources :announcements
      resources :requests do
        patch :process_state
        patch :complete_state
      end
    end
    root 'admin/home#index', as: :admin_root
  end

  constraints(BarangayDomainConstraint.new) do
    scope module: 'barangay' do
      devise_for :users, controllers: {
        sessions: 'barangay/users/sessions',
        confirmations: 'barangay/users/confirmations',
        mailers: 'barangay/users/mailers',
        passwords: 'barangay/users/passwords',
        registrations: 'barangay/users/registrations',
        shared: 'barangay/users/shared',
        unlocks: 'barangay/users/unlocks'
      }, as: :barangay
      resources :users
      resources :home
      resources :resources
      resources :requests
    end
    root 'barangay/home#index', as: :barangay_root
    get '/requests/new', to: 'barangay/requests#new', as: :new_barangay_request
    post '/requests', to: 'barangay/requests#create', as: :create_barangay_request
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminApplicationController
  before_action :authenticate_admin_user!
  def index
    @announcements = Announcement.all
  end
end

app/controllers/barangay/home_controller.rb
class Barangay::HomeController < ApplicationController
  before_action :authenticate_barangay_user!
  def index
    @announcements = Announcement.order(created_at: :desc).page(params[:page]).per(2)
  end
end

app/controllers/barangay/requests_controller.rb
class Barangay::RequestsController < ApplicationController
  before_action :set_params, only: [:create, :update]

  def index
    @requests = Request.where(user: current_barangay_user)
                      .page(params[:page]).per(2)
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(set_params)
    @request.state = 'pending'
    @request.firstname = current_barangay_user.firstname
    @request.user_id = current_barangay_user.id

    if @request.save
      flash[:notice] = 'Request was successfully created.'
      redirect_to barangay_root_path
    else
      flash[:notice] = 'Request was NOT created.'
      redirect_to barangay_root_path
    end
  end

  private

  def set_params
    params.require(:request).permit(:requested_document, :document_purpose, :message)
  end
end

app/controllers/barangay/users/confirmations_controller.rb
# frozen_string_literal: true

class Barangay::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/barangay/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Barangay::Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # users :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/barangay/users/passwords_controller.rb
# frozen_string_literal: true

class Barangay::Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/barangay/users/registrations_controller.rb
# frozen_string_literal: true

class Barangay::Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/barangay/users/sessions_controller.rb
# frozen_string_literal: true

class Barangay::Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/barangay/users/unlocks_controller.rb
# frozen_string_literal: true

class Barangay::Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/barangay/home/index.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="container-fluid">
  <div class="row">
    <!-- Sidebar -->
    <div class="col-md-3 bg-primary text-white vh-100 p-3">
      <h3 class="text-center mb-4">BRGY. 790</h3>
      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to 'Announcement', home_index_path, class: 'nav-link text-white' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add request', new_barangay_request_path, class: 'nav-link text-white' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Request History', requests_path, class: 'nav-link text-white' %>
        </li>
      </ul>
      <div class="mt-4">
        <button class="btn btn-light w-100 mb-2">Edit Profile</button>
        <%= button_to 'Log out', destroy_barangay_user_session_path, method: :delete, class:'btn btn-danger w-100' %>
      </div>
    </div>

    <!-- Main Content -->
    <div class="col-md-9">
      <!-- Header Section -->
      <div class="d-flex justify-content-between align-items-center p-3">
        <h4>Announcements</h4>
        <input type="date" class="form-control w-25" id="announcement_date">
      </div>

      <!-- Announcements List -->
      <div class="p-3">
        <% @announcements.each do |announcement| %>
          <div class="card mb-3">
            <div class="card-body">
              <h5 class="card-title"><%= announcement.title %></h5>
              <p class="card-text"><%= announcement.description %></p>
              <p class="text-muted small mb-0">Posted on <%= announcement.created_at.strftime('%B %d, %Y, %I:%M %p') %></p>
            </div>
          </div>
        <% end %>

        <!-- Pagination -->
        <div class="d-flex justify-content-center mt-3">
          <%= paginate @announcements %>
        </div>
      </div>
    </div>
  </div>
</div>